config/routes.rb
Rails.application.routes.draw do
    root 'emotions#index'
    
    get '/login', to: redirect('/auth/google_oauth2')
    get '/logout' => 'sessions#destroy', :as => :logout
    get "/auth/:provider/callback" => "sessions#create"
    
    resources :emotions
end

app/models/emotion.rb
class Emotion < ActiveRecord::Base
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :emotions
    
    def self.create_with_omniauth(auth)
      create! do |user|
        user.provider = auth["provider"]
        user.uid = auth["uid"]
        user.name = auth["info"]["name"]
        user.email = auth["info"]["email"]
        user.image = auth["info"]["image"]
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user
  helper_method :require_valid_user
  
  def current_user
      begin
          @current_user ||= User.find(session[:user_id]) if session[:user_id]
      rescue
          @current_user = nil
      end
  end
  
  def require_valid_user
      if session[:user_id] == nil || current_user == nil
          respond_to do |format|
              flash[:warning] = "Must be logged in to do that."
              format.html { redirect_to login_path }
          end
      end
  end
end

app/controllers/emotions_controller.rb
class EmotionsController < ApplicationController
    before_filter :require_valid_user
    
    def index
        @emotions = current_user.emotions.paginate(:page => 1, :per_page => 10)
    end
    
    def new
        @emotion = current_user.emotions.new
    end
    
    def create
        @emotion = current_user.emotions.create(emotion_params)
        
        if @emotion.save
            redirect_to emotions_path
        else
            render 'new'
        end
    end
    
    def show
        @emotion = current_user.emotions.find(params[:id])
    end
    
    def edit
        @emotion = current_user.emotions.find(params[:id])
    end
    
    def update
        @emotion = current_user.emotions.find(params[:id])
        
        if @emotion.update(emotion_params)
            redirect_to emotions_path
        else
            render 'edit'
        end
    end
    
    def destroy
        @emotion = current_user.emotions.find(params[:id])
        
        if @emotion.destroy
            redirect_to emotions_path
        else
            render 'show'
        end
    end
    
    def emotion_params
        params.require(:emotion).permit(:name, :description, :latitude, :longitude)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    def create
      auth = request.env["omniauth.auth"]
      user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
      session[:user_id] = user.id
      flash[:success] = "Signed in!"
      redirect_to root_url
    end

    def destroy
      session[:user_id] = nil
      flash[:success] = "Signed out!"
      redirect_to root_url
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emotions_helper.rb
module EmotionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/emotions/_emotion.html.erb
<div class="col-md-3">
    <div class="panel panel-default">
        <div class="panel-heading"><strong><%= emotion.name %></strong></div>
        <div class="panel-body"><%= emotion.description %></div>
        <div class="panel-footer">
            <div class="small">
                <% if emotion.latitude && emotion.longitude %>
                <%= emotion.latitude %>, <%= emotion.longitude %><br>
                <% end %>
                <%= emotion.created_at %>
            </div>
        </div>
    </div>
</div>

app/views/emotions/index.html.erb
<div class="row text-center">
    <%= link_to "I'm feeling...", new_emotion_path, :class => "btn btn-default" %>
</div>

<br>

<div class="row text-center">
    
    <% if @emotions.count > 0 %>
    <%= render @emotions %>
    <%= will_paginate @emotions, renderer: BootstrapPagination::Rails %>
    <% else %>
    <h2>Nothing to see here!</h2>
    <% end %>

</div>

app/views/emotions/new.html.erb
<%= form_for @emotion, :html => { :role => :form, :class => "container" } do |f| %>

<div class="form-horizontal">
    <div class="form-group">
        <%= f.label 'What are you feeling?', :class => "col-sm-4 control-label" %>
        <div class="col-sm-4">
            <%= f.text_field :name, :class => "form-control" %>
        </div>
    </div>
    <div class="form-group">
        <%= f.label 'Why?', :class => "col-sm-4 control-label" %>
        <div class="col-sm-4">
            <%= f.text_field :description, :placeholder => "optional", :class => "form-control" %>
        </div>
    </div>
    <div class="form-group">
        <%= f.label 'Latitude', :class => "col-sm-4 control-label" %>
        <div class="col-sm-4">
            <%= f.text_field :latitude, :class => "form-control" %>
        </div>
    </div>
    <div class="form-group">
        <%= f.label 'Longitude', :class => "col-sm-4 control-label" %>
        <div class="col-sm-4">
            <%= f.text_field :longitude, :class => "form-control" %>
        </div>
    </div>
    
    <div class="text-center">
        <%= f.submit 'Create', :class => "btn btn-default" %>
    </div>
</div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>bundlejoy</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
        
    <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mainNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">bundlejoy</a>
            </div>
            <div class="collapse navbar-collapse" id="mainNavbar">
                <ul class="nav navbar-nav" role="tablist">
                    <li><%= link_to 'home', root_path %></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    
                    <% if current_user %>
                        
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <%= current_user.name %>
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><%= link_to 'Sign Out', logout_path %></li>
                        </ul>
                    </li>
                        
                    <% else %>
                    
                    <li><%= link_to 'Sign In', login_path %></li>
                    
                    <% end %>
                </ul>
            </div>
        </div>
    </nav>
        
    
    <div class="container">
       
        <div class="row text-center">
            <div class="col-md-8 col-md-offset-2">
                <% flash.each do |name, msg| %>
                <%= content_tag :div, msg, :class => "alert alert-#{name}" %>
                <% end %>
            </div>
        </div>
            
        <div class="row">

            <%= yield %>
        
        </div>

        <div class="row text-center small">
            <br><br>
            questions? bugs? feature requests? email <a href="mailto:mitchell.rysavy@gmail.com">mitchell</a>.
        </div>

    </div>

</body>
</html>